version: '3.9'

services:
  back-end:
    container_name: back
    build:
      context: ./back-end
    ports:
      - 4000:4000
    volumes:
      - ./back-end:/back-end
      - /back-end/node_modules
    networks:
      - app-network

  front-end:
    container_name: front
    build:
      context: ./front-end
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/front-end
      - /front-end/node_modules
    working_dir: /front-end
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge