version: '3.9'

services:
  back-end:
    container_name: back
    build:
      context: ./back-end
    ports:
      - 4000:4000
    volumes:
      - ./back-end:/app
      - /app/node_modules
    networks:
      - app-network

  front-end:
    container_name: front
    build:
      context: ./front-end
    ports:
      - 8081:8081
    volumes:
      - ./front-end:/front-end
      - /front-end/node_modules
    working_dir: /front-end
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge